### ISSUE TITLE
Agregar "prefiero no responder" a las preguntas que NO inician el proceso de accesibilidad. 

### ISSUE THREAD

**Issue by eliocamp** [MetaDocencia/Cursos#5]

**Comment by paocorrales** [comment]
Holiii
El proceso de accesibilidad se activa también si:

¿Tienes alguna de las siguientes dificultades para participar de talleres en forma remota? Marca todas las que correspondan.: No tengo ninguna de estas dificultades
**Si marcaste que tenés alguna dificultad, ¿cómo podemos facilitar tu participación? Marca todas las que correspondan.: Hablando claro, pausado, con buena calidad de audio**

**Comment by eliocamp** [comment]
Pregunté en el whatsapp del grupo de accesibilidad a ver si un caso como ese puede pasar automáticamente por el proceso general.
