### ISSUE TITLE
Learnr - sistema de inscripción

### ISSUE THREAD

**Issue by paocorrales** [MetaDocencia/Cursos#6]
- [x] Armar planilla de pre-inscripción y botón para embeber en la web
- [x] Armar evento en calendly
    - [x] Armar mail de confirmación que incluya los paquetes que tienen que tener instalados para participar

**Comment by paocorrales** [comment]
@yabellini que te parece este mensaje cuando las personas se pre-inscriben al curso? Pensando en el feedback que ya tuvimos:

> Hola Paola,
> 
> Recibimos tu pre-inscripciónn al Taller de {learnr}, ¡muchas gracias por tu interés!
> 
> Apenas tengamos disponibilidad te enviaremos un mail de invitación para que puedas elegir el día y horario que prefieras para realizarlo.
> 
> Ten en cuenta que este es un taller pensado para personas que usan el lenguaje R y les gustaría generar tutoriales interactivos para sus clases u otros proyectos. Por eso asumiremos que tenés algo de experiencia usando R, la interfaz de RStudio y archivos RMarkdown.
> 
> Por favor, usa siempre tu mail xxx para pre-inscribirte a los cursos y actividades de MetaDocencia
> 
> Nos vemos en Slack, Facebook y Twitter.
> 
> ¡Saludos!
> El equipo de MetaDocencia
> 
> Este mensaje fue generado automáticamente, por favor no responder.

**Comment by yabellini** [comment]
Me parece muy bien Pao. Gracias!
